# Alterara a eliminação Gaussiana para utilizar uma matriz triangular inferior
# Eliminação gaussiana sem pivoteamento

In [ ]:
import numpy as np
import pandas as pd # utilizado apenas na impressão de algumas matrizes

1. **Inicialize uma matriz A de dimensão $3\times 3$ e uma matriz $b$ de dimensão $3 \times 1$ com números aleatórios.**

In [ ]:
# np.random.seed(2)

A = np.array([[3, 2, 7], [-6, 5, 1], [3, 11, -1]])
b = np.array([[8], [-10], [-9]])

Vamos utilizar a eliminação gaussiana para determinar $x$, de modo que $Ax = b$. O python será utilizado como uma calculadora. Para preserver as matrizes `A` e `b` vamos cópias `copia_A` e `copia_b`.

In [ ]:
copia_A = np.copy(A)
copia_b = np.copy(b)
print(A)

[[ 3  2  7]
 [-6  5  1]
 [ 3 11 -1]]


In [ ]:
print(b)

[[  8]
 [-10]
 [ -9]]


**2. Qual o valor do primeiro multiplicador? Não utilize os números e sim referências a matriz.**

In [ ]:
pivo = A[0, 0]
m = -A[1, 0] / pivo

Adicione $m \cdot linha0$ a $linha 1$.

In [ ]:
A[1] = A[1] + m * A[0]
b[1] = b[1] + m * b[0]

In [ ]:
# Se sua resposta estiver certa A[1,0] será = 0
print(A)
print()
print(b)


[[ 3  2  7]
 [ 0  9 15]
 [ 3 11 -1]]

[[ 8]
 [ 6]
 [-9]]


**3. Determine o próximo multiplicador? E atualize a linha 2 das matrizes A e b.**

In [ ]:
m = - A[2, 0] / pivo
A[2] = A[2] + m * A[0]
b[2] = b[2] + m * b[0]

In [ ]:
# Sua resposta está correta? 
print(A)
print()
print(b)

[[ 3  2  7]
 [ 0  9 15]
 [ 0  9 -8]]

[[  8]
 [  6]
 [-17]]


**4. O trabalho com a primeira coluna está finalizado. Determine o próximo pivô.**

In [ ]:
pivo = A[1, 1]

**5. Determine o próximo multiplicador e atualize a linha 2.**

In [ ]:
m = - A[2, 1] / pivo
A[2] = A[2] + m * A[1]
b[2] = b[2] + m * b[1]

In [ ]:
print('A= \n', A)
print()
print('b= \n', b)

A= 
 [[ 0.13457995  0.51357812  0.18443987]
 [ 0.         -2.14298647 -0.58205361]
 [ 0.          0.          0.20087526]]

b= 
 [[ 0.0652865 ]
 [ 0.0471459 ]
 [-0.38346875]]


Agora a matriz A está em um formato triangular superior e precisamos determinar os valores de `x[0]`, `x[1]` e `x[2]`.

In [ ]:
x = np.zeros(3, dtype=float)

In [ ]:
x

array([0, 0, 0])

**6. Determine o valor de `x[2]`.**

In [ ]:
x[2] = b[2] / A[2, 2]
x[2]

2

**7. Determine o valor de `x[1]`.**

In [ ]:
x[1] = (b[1] - A[1, 2] * x[2]) / A[1, 1]

**8. Determine o valor de x[0].**

In [ ]:
x[0] = (b[0] - A[0, 1] * x[1] - A[0, 2] * x[2]) / A[0, 0]
x

array([ 1.20664189,  0.4964979 , -1.90898943])

Verificando o resultado

In [ ]:
copia_A @ x

array([0.0652865 , 0.42812233, 0.09653092])

In [ ]:
copia_b

array([[0.0652865 ],
       [0.42812233],
       [0.09653092]])

**9. Combine o código que você escreveu até agora para resolver sistemas lineares com 3 equações e 3 incógnitas.**

In [ ]:
def eliminacao_gaussiana_3(matriz_coeficientes, termos_independentes):
    '''
    matriz_coeficientes é uma matriz 3 por 3
    termos_independentes é uma matriz 3 por 1
    Não será necessário realizar pivoteamento, se o pivo for igual a zero ocorrerá um erro (divisão por zero)
    '''
    A = np.copy(matriz_coeficientes)
    b = np.copy(termos_independentes)
    
    # seu código aqui
    pivo = A[0, 0]
    
    m = -A[1, 0] / pivo
    A[1] = A[1] + m * A[0]
    b[1] = b[1] + m * b[0]

    m = - A[2, 0] / pivo
    A[2] = A[2] + m * A[0]
    b[2] = b[2] + m * b[0]

    pivo = A[1, 1]
    m = - A[2, 1] / pivo
    A[2] = A[2] + m * A[1]
    b[2] = b[2] + m * b[1]

    x = np.zeros(3)
    x[2] = b[2] / A[2, 2]
    x[1] = (b[1] - A[1, 2] * x[2]) / A[1, 1]
    x[0] = (b[0] - A[0, 1] * x[1] - A[0, 2] * x[2]) / A[0, 0]
    
    return x

In [ ]:
A1 = np.random.rand(3, 3)
b1 = np.random.rand(3, 1) 

In [ ]:
x = eliminacao_gaussiana_3(A1, b1)

In [ ]:
y = A1 @ x
print('b1 = ', b1)
print('y  = ', y)

b1 =  [[0.48306984]
 [0.50523672]
 [0.38689265]]
y  =  [0.48306984 0.50523672 0.38689265]


Agora vamos inicializar uma matriz A com dimensão $5 \times 5$ e uma matriz $b$ com dimensão $5 \times 1$.

In [ ]:
A = np.random.rand(5, 5)
b = np.random.rand(5, 1)

In [ ]:
print(A)

[[0.54790778 0.69952062 0.24581116 0.18662715 0.11058315]
 [0.27405925 0.01025004 0.62935972 0.29517231 0.18728654]
 [0.09528805 0.28375581 0.21492438 0.28560373 0.47140986]
 [0.54949682 0.84511312 0.9885097  0.04886809 0.23211825]
 [0.64331143 0.16146656 0.87014589 0.21740243 0.74175504]]


**10. Realize operações sobre linhas para zerar os valores abaixo do pivô.**

In [ ]:
pivo = A[0 , 0]

for k in range(1, 5):
  m = - A[k ,0] / pivo
  A[k] = A[k] + m * A[0]
  b[k] = b[k] + m * b[0]

In [ ]:
pd.DataFrame(A)

0         1         2         3         4
0  0.547908  0.699521  0.245811  0.186627  0.110583
1  0.000000 -0.339645  0.506407  0.201823  0.131974
2  0.000000  0.162100  0.172175  0.253147  0.452178
3  0.000000  0.143564  0.741986 -0.138300  0.121214
4  0.000000 -0.659857  0.581533 -0.001721  0.611917

Agora vamos inicializar uma matriz A com dimensão $10 \times 10$ e uma matriz $b$ com dimensão $10 \times 1$.

In [ ]:
A = np.random.rand(10, 10)
b = np.random.rand(10, 1)

**11. Escreva um código para zerar os elementos abaixo do pivô da coluna 0**

In [ ]:
pivo = A[0 , 0]

for k in range(1, 10):
    m = - A[k ,0] / pivo
    A[k] = A[k] + m * A[0]
    b[k] = b[k] + m * b[0]
    A[k, 0] = 0

In [ ]:
pd.DataFrame(A)

0         1         2         3         4         5         6  \
0  0.641812  0.087379  0.715731  0.101745  0.175599  0.713322  0.885264   
1  0.000000  0.546999  0.083252  0.500485  0.584912  0.735644  0.202663   
2  0.000000  0.639165  0.101169  0.841468  0.662343 -0.130555 -0.883960   
3  0.000000  0.703291 -0.469396  0.321858  0.244932 -0.731962 -0.829324   
4  0.000000  0.368924  0.063367  0.192343  0.934445  0.338874  0.688795   
5  0.000000  0.164656 -0.040218  0.524902  0.255866 -0.625938 -0.908566   
6  0.000000  0.241630  0.894672  0.549966  0.345619 -0.038885  0.193562   
7  0.000000  0.035312 -0.128028  0.464602  0.014216  0.709926 -0.073420   
8  0.000000  0.167551 -0.080522  0.065817  0.600735  0.284951 -0.134720   
9  0.000000  0.253830  0.346367  0.765265  0.697984  0.372828 -0.719135   

          7         8         9  
0  0.983138  0.652907  0.477736  
1  0.854388  0.905645  0.760806  
2 -0.439930 -0.352939 -0.351918  
3 -0.931498 -0.893550  0.228072  
4  0.081509  0.221630  0.859538  
5 -0.431674 -0.225578 -0.138272  
6  0.187608  0.126444  0.312608  
7  0.153791  0.208516  0.140495  
8  0.384712  0.057254  0.370269  
9 -0.309281  0.405700 -0.254997

**12. Escreva um código para zerar os elementos abaixo do pivô da coluna 1**

In [ ]:
pivo = A[1 , 1]

for k in range(2, 10):
    m = - A[k ,1] / pivo
    A[k] = A[k] + m * A[1]
    b[k] = b[k] + m * b[1]
    # A[k, 1] = 0
    

In [ ]:
pd.DataFrame(A)

0             1         2         3         4         5         6  \
0  0.641812  8.737918e-02  0.715731  0.101745  0.175599  0.713322  0.885264   
1  0.000000  5.469990e-01  0.083252  0.500485  0.584912  0.735644  0.202663   
2  0.000000  0.000000e+00  0.003890  0.256654 -0.021122 -0.990150 -1.120771   
3  0.000000 -1.110223e-16 -0.576435 -0.321629 -0.507104 -1.677798 -1.089894   
4  0.000000  0.000000e+00  0.007217 -0.145210  0.539951 -0.157282  0.552108   
5  0.000000  0.000000e+00 -0.065278  0.374247  0.079797 -0.847380 -0.969571   
6  0.000000  0.000000e+00  0.857897  0.328883  0.087242 -0.363846  0.104038   
7  0.000000  0.000000e+00 -0.133403  0.432293 -0.023543  0.662436 -0.086503   
8  0.000000  0.000000e+00 -0.106023 -0.087486  0.421571  0.059616 -0.196798   
9  0.000000  0.000000e+00  0.307734  0.533019  0.426561  0.031459 -0.813180   

          7         8         9  
0  0.983138  0.652907  0.477736  
1  0.854388  0.905645  0.760806  
2 -1.438276 -1.411179 -1.240914  
3 -2.030006 -2.057962 -0.750115  
4 -0.494734 -0.389184  0.346411  
5 -0.688860 -0.498193 -0.367288  
6 -0.189807 -0.273613 -0.023468  
7  0.098635  0.150051  0.091380  
8  0.123005 -0.220153  0.137227  
9 -0.705752 -0.014557 -0.608043

**13. Escreva um código para zerar os elementos abaixo do pivô da coluna 2**

In [ ]:
pivo = A[2 , 2]

for k in range(3, 10):
    m = - A[k ,2] / pivo
    A[k] = A[k] + m * A[2]
    b[k] = b[k] + m * b[2]
    # A[k, 0] = 0
    

In [ ]:
A = np.random.rand(10, 10)
b = np.random.rand(10, 1)

for j in range(0, 9):
  pivo = A[j , j]

  for k in range(j+1, 10):
      m = - A[k ,j] / pivo
      A[k] = A[k] + m * A[j]
      b[k] = b[k] + m * b[j]
      A[k, j] = 0
pd.DataFrame(A)

0          1          2         3         4          5          6  \
0  0.012051   0.207087   0.479008  0.162310  0.068688   0.492511   0.903145   
1  0.000000 -10.068226 -24.300268 -8.323395 -2.875402 -25.659218 -46.592932   
2  0.000000   0.000000  -0.883384  0.138818  0.551405  -0.519687  -2.054984   
3  0.000000   0.000000   0.000000  1.431620  0.883286   1.714544  -1.352149   
4  0.000000   0.000000   0.000000  0.000000 -1.139367  -0.569660   0.933051   
5  0.000000   0.000000   0.000000  0.000000  0.000000  -0.246650   1.728106   
6  0.000000   0.000000   0.000000  0.000000  0.000000   0.000000   4.514689   
7  0.000000   0.000000   0.000000  0.000000  0.000000   0.000000   0.000000   
8  0.000000   0.000000   0.000000  0.000000  0.000000   0.000000   0.000000   
9  0.000000   0.000000   0.000000  0.000000  0.000000   0.000000   0.000000   

          7          8          9  
0  0.011501   0.228078   0.901320  
1  0.351872 -11.843244 -46.623044  
2  0.021328   0.269376  -2.489456  
3 -0.967667   1.810584  -1.932585  
4  0.737188  -0.945586   1.386234  
5 -0.347998   0.062790   1.712365  
6 -0.731263   0.106697   5.859311  
7  1.240021  -0.272940   1.345171  
8  0.000000  -0.026213   0.884396  
9  0.000000   0.000000   7.056261

**14. Existe repetição nesses códigos. Agora escreva um laço para zerar os elementos abaixo do pivô da coluna k.**

In [ ]:
k = 3



In [ ]:
pd.DataFrame(A)

**15. Escreva uma função que realize a primeira parte da eliminação gaussiana, convertendo a matriz em uma matriz triangular superior.**

In [ ]:
def eliminacao_gaussiana(matriz_coeficientes, termos_independentes):
    '''
    matriz_coeficientes é uma matriz quadrada
    termos_independentes é um vetor
    Não será necessário realizar pivoteamento, se o pivo for igual a zero ocorrerá um erro (divisão por zero)
    '''
    
    A = np.copy(matriz_coeficientes)
    b = np.copy(termos_independentes)
    tamanho = len(A)

    for j in range(0, tamanho-1):
      pivo = A[j , j]

      for k in range(j+1, tamanho):
          m = - A[k ,j] / pivo
          A[k] = A[k] + m * A[j]
          b[k] = b[k] + m * b[j]
          A[k, j] = 0
    
    
    return A, b

In [ ]:
# np.random.seed(1)
tA = np.random.rand(6, 6)
tb = np.random.rand(6, 1)

A, b = eliminacao_gaussiana(tA, tb)

In [ ]:
pd.DataFrame(A)

0         1         2         3         4         5
0  0.37658  0.973784  0.604716  0.828846  0.574712  0.628076
1  0.00000 -0.151627  0.291441  0.229766  0.319255  0.221761
2  0.00000  0.000000 -4.393870 -4.350284 -4.964547 -3.828480
3  0.00000  0.000000  0.000000 -0.151408  0.434549  0.181008
4  0.00000  0.000000  0.000000  0.000000  1.616937  1.012070
5  0.00000  0.000000  0.000000  0.000000  0.000000 -0.077152

In [ ]:
pd.DataFrame(b)

0
0  0.572489
1  0.299001
2 -4.567036
3  0.202882
4  0.739567
5  0.118094

**16. Agora precisamos determinar as soluções do sistema.**

In [ ]:
x = np.zeros(6)

x[5] = b[5] / A[5, 5]


x[4] = (b[4] - A[4,5] * x[5]) / A[4, 4]
x[3] = (b[3] - A[3,4] * x[4] - A[3,5] * x[5]) / A[3, 3]

# x2
x[2] = b[2]
for k in range(3, 6):
  x[2] = x[2] - A[2,k] * x[k]

x[2] = x[2] / A[2, 2]

# x1
x[1] = b[1]
for k in range(2, 6):
  x[1] = x[1] - A[1,k] * x[k]

x[1] = x[1] / A[1, 1]

# x0
x[0] = b[0]
for k in range(1, 6):
  x[0] = x[0] - A[0,k] * x[k]

x[0] = x[0] / A[0, 0]
x

4
2
0


array([ 0.31818795, -0.38773708,  1.1740851 ,  0.07046076,  0.36290187,
       -0.61822813])

In [ ]:
x = np.zeros(6)

x[5] = b[5] / A[5, 5]

for j in range(4, -1, -1):
  # xj
  x[j] = b[j]
  for k in range(j+1, 6):
    x[j] = x[j] - A[j,k] * x[k]

  x[j] = x[j] / A[j, j]

In [ ]:
tA @ x

array([0.57248852, 0.73314253, 0.51901163, 0.77088391, 0.56885799,
       0.46570988])

In [ ]:
tb

array([[0.57248852],
       [0.73314253],
       [0.51901163],
       [0.77088391],
       [0.56885799],
       [0.46570988]])

In [ ]:
x[2] = b[2]

for k in range(3, 6):
  x[2] = x[2] - A[2,k] * x[k]

x[2] = x[2] / A[2, 2]
x[2]

21.91792063032234

**17. Existe uma repetição no código acima, escreva um laço que calcule os valores de x[k] com k variando de 9 até 0.**

In [ ]:
x[9] = tb[9] / tA[9, 9]

for k in range(8, -1, -1):
    pass

In [ ]:
x

In [ ]:
A @ x

In [ ]:
b

**18. Escreva uma função que determine as soluções de um sistema com matriz de coeficientes triangular superior**

In [ ]:
def triangular_superior(matriz_coeficientes, termos_independentes):
    '''
    matriz_coeficientes: matriz triangular superior
    termos_independentes: termos independentes do sistema retangular superior
    
    retorna a solução do sistema
    '''
    tamanho = len(matriz_coeficientes)
    A = np.copy(matriz_coeficientes)
    b = np.copy(termos_independentes)
    
    
    x = np.zeros(tamanho)

    x[tamanho-1] = b[tamanho-1] / A[tamanho-1, tamanho-1]

    for j in range(tamanho-2, -1, -1):
      # xj
      x[j] = b[j]
      for k in range(j+1, tamanho):
        x[j] = x[j] - A[j,k] * x[k]

      x[j] = x[j] / A[j, j]
    
    return x

In [ ]:
A = np.random.rand(10, 10)
b = np.random.rand(10, 1)
A[0, 0] = 1e-16
tA, tb = eliminacao_gaussiana(A, b)
x = triangular_superior(tA, tb)

In [ ]:
A @ x

array([  0.71131452, -14.16581471,  -1.72781723, -23.95997699,
       -41.09378377, -18.15340895,  -0.53363778,  -5.91230034,
       -36.46486113,  -2.51926731])

In [ ]:
b

array([[0.71131452],
       [0.55388461],
       [0.30451799],
       [0.83485405],
       [0.43530596],
       [0.92345622],
       [0.7060518 ],
       [0.47803131],
       [0.1262101 ],
       [0.97604355]])

**19. Combine as funções `eliminação_gaussiana` e `triangular_superior` para resolver um sistema de equações Ax=b com $det(A) \neq 0$**

In [ ]:
def resolver_sistema(matriz_coeficientes, termos_independentes):
    tA, tb = eliminacao_gaussiana(matriz_coeficientes, termos_independentes)
    x = triangular_superior(tA, tb)
    
    return x

In [ ]:
A = np.random.rand(10, 10)
b = np.random.rand(10, 1)

x = resolver_sistema(A, b)


In [ ]:
A @ x

array([0.78445742, 0.4569657 , 0.65622933, 0.13184098, 0.43298151,
       0.90931199, 0.605479  , 0.76677459, 0.50470061, 0.49805562])

In [ ]:
b

array([[0.78445742],
       [0.4569657 ],
       [0.65622933],
       [0.13184098],
       [0.43298151],
       [0.90931199],
       [0.605479  ],
       [0.76677459],
       [0.50470061],
       [0.49805562]])

In [ ]:
np.linalg.solve(A, b)

array([[-0.6841543 ],
       [ 0.00706757],
       [-2.10675158],
       [-0.58965077],
       [ 0.01130338],
       [ 1.16777685],
       [ 1.22755891],
       [ 0.97888001],
       [ 0.06630452],
       [ 1.29909078]])